spring:
  application:
    name: eureka-student
server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka

eureka-grade:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule